### PR TITLE
Fix for new builf gradle plugin

### PR DESCRIPTION
**Pull request by Fornori**
Fix for latest gradle build plugin

### CODE REVIEW

**Comment by bluesliverx** [comment]
Thanks for the PR, I just don't have time or need to maintain this anymore, especially since Jenkins has it's own plugin to do about the same thing now.  I'll merge this, but I have no idea if it'll deploy to maven central, etc.

**Comment by Fornori** [comment]
I use this plugin with Atlassian Bamboo. $)

**Comment by bluesliverx** [comment]
@Fornori, this finally built, so you should be able to grab the latest 0.6-SNAPSHOT.

**Comment by Fornori** [comment]
Thanks. $)

**Pull request merged**
